name: Build and Push Web

on:
  push:
    #commenting this out while testing workflows on terraform-dev branch
    #branches: 
    #  - main
    paths:
      - 'app/web/**'

env:
  TAG: prod

jobs:
  build-and-push:
    name: build-and-push
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: build-tag-push
        run: make build-push-web ${{ env.TAG }}