name: Build and Push Web

on:
  push:
    #commenting this out while testing workflows on terraform-dev branch
    #branches: 
    #  - main
    paths:
      - 'app/web/**'

env:
  TAG: prod

jobs:
  build-and-push-web:
    name: build-and-push-web
    runs-on: ubuntu-20.04
      
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2
      
      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with: 
          token_format: access_token
          workload_identity_provider: projects/746527132086/locations/global/workloadIdentityPools/github-actions-identity-pool/providers/github-actions-identity-provider
          service_account: deployment-pipeline-service-ac@project-ct-sandbox.iam.gserviceaccount.com
          access_token_lifetime: 300s
        
      - name: Login to Google Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: northamerica-northeast2-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: build-tag-push
        run: make build-push-web ${{ env.TAG }}